name: Deployment Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job_one:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: Strato Server
    steps:
      - name: Change directory to project root
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami