name: Deployment Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  host: h2948228.stratoserver.neth2948228.stratoserver.net
  key: ${{ secrets.SSH_PRIVATE_KEY}}
  port: 22

jobs:
  job_one:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Change directory to project root
        uses: appleboy/ssh-action@master
        with:
          host: $host
          port: $port
          key: $key
          script: |
            echo "Change directory to /home/felix/ZKS-Backend"
            cd /home/felix/ZKS-Backend
      - name: Kill all running processes
        uses: appleboy/ssh-action@master
        with:
          host: $host
          port: $port
          key: $key
          script: |
            echo "Kill all running processes"
            killall -9 java
      - name: Run Tests and start application
        uses: appleboy/ssh-action@master
        with:
          host: $host
          port: $port
          key: $key
          script: |
            echo "Pull latest changes from Main"
            git pull origin main
            echo "Run Tests"
            mvn clean test
            if [ $? -eq 0 ]; then
              echo "Successfully ran tests"
              echo "Start Server"
              mvn spring-boot:run
              exit 0
            else
              echo "Test failed"
              echo "Exiting Deployment"
              exit 1
            fi